# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: PR Checks

on:
  pull_request:
    branches: ["main"]

permissions:
  pull-requests: read

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check prefix
        run: node ./test/pull-request.mjs --title="${{ github.event.pull_request.title }}"
